plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: 
    - kube-master
  instance-state-name: running  
keyed_groups:
  - key: tags['Name']
    prefix: 'all_instances'
hostnames:
  - "ip-address"    
compose:
  ansible_user: "'ubuntu'"