apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
spec:
  ingressClassName: nginx
  rules:
    - host: '{{ .Values.DNS_NAME }}'
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: ozguryzl-service
              port:
                number: 8080
status:
  loadBalancer: {}