apiVersion: v1
kind: Service
metadata:
  name: ozguryzl-service
  labels:
    name: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - name: "8080"
      nodePort: 30001
      port: 8080
      targetPort: 8080
  type: NodePort 