apiVersion: v1
kind: Service
metadata:
  name: ozguryzl-service
  namespace: ozguryzl-dev
  labels:
    name: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - name: "app"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800