mykey = "yaksonkey"
ami = "ami-0e001c9271cf7f3b9"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "ozguryzl-jenkins-server-secgr"
jenkins-server-tag = "Jenkins Server of ozguryzl"
jenkins-profile = "ozguryzl-jenkins-server-profile"
jenkins-role = "ozguryzl-jenkins-server-role"
